// Auto-generated file - do not edit manually
// This file is generated by scripts/extract-photo-dates.js
// Run: npm run extract-photo-dates

export const PHOTO_DATES: Record<string, string> = {
  "121224_JoshHartlep-44": "2024-12-14T20:53:49.000Z",
  "121224_JoshHartlep-51": "2024-12-14T19:47:14.000Z",
  "2025-11-12 AG Jeff Jackson 01": "2025-11-12T23:15:28.000Z",
  "2025-11-12 AG Jeff Jackson 02": "2025-11-12T22:46:52.000Z",
  "2025-11-12 AG Jeff Jackson 03": "2025-11-12T22:59:07.000Z",
  "20250203_Gardens_JoshuaHartlep-17": "2025-02-03T21:19:20.000Z",
  "20250203_Gardens_JoshuaHartlep-33": "2025-02-03T21:59:20.000Z",
  "Duke Chapel 1": "2024-09-12T14:30:14.000Z",
  "Duke Chapel 2": "2024-09-10T16:00:30.000Z",
  "Hartlep_DukeSnow011024-1": "2025-01-11T02:20:03.000Z",
  "Hartlep_DukeSnow011024-4": "2025-01-11T02:14:17.000Z",
  "JoshHartlep_Gardens_011324-12": "2025-01-13T18:35:15.000Z",
  "JoshHartlep_Gardens_011324-15": "2025-01-13T18:47:30.000Z",
  "WI Bird 1": "2023-09-11T22:21:20.000Z",
  "WI Bird 2": "2023-11-22T21:49:07.000Z"
};
